import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
            },
            colors: {
                primary: '#3525cd',
                'primary-container': '#4f46e5',
                'on-primary': '#ffffff',
                'primary-fixed': '#e2dfff',
                'primary-fixed-dim': '#c3c0ff',
                'on-primary-container': '#dad7ff',
                'on-primary-fixed': '#0f0069',
                'on-primary-fixed-variant': '#3323cc',
                'inverse-primary': '#c3c0ff',
                surface: '#f9f9ff',
                'surface-dim': '#d3daea',
                'surface-bright': '#f9f9ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f0f3ff',
                'surface-container': '#e7eefe',
                'surface-container-high': '#e2e8f8',
                'surface-container-highest': '#dce2f3',
                'surface-variant': '#dce2f3',
                'surface-tint': '#4d44e3',
                'on-surface': '#151c27',
                'on-surface-variant': '#464555',
                'on-background': '#151c27',
                'inverse-surface': '#2a313d',
                'inverse-on-surface': '#ebf1ff',
                background: '#f9f9ff',
                secondary: '#575e70',
                'secondary-container': '#d9dff5',
                'on-secondary': '#ffffff',
                'on-secondary-fixed': '#141b2b',
                'on-secondary-fixed-variant': '#404758',
                'on-secondary-container': '#5c6274',
                'secondary-fixed': '#dce2f7',
                'secondary-fixed-dim': '#c0c6db',
                outline: '#777587',
                'outline-variant': '#c7c4d8',
                error: '#ba1a1a',
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
                'on-error-container': '#93000a',
                tertiary: '#7e3000',
                'tertiary-container': '#a44100',
                'on-tertiary': '#ffffff',
                'on-tertiary-fixed': '#351000',
                'on-tertiary-container': '#ffd2be',
                'tertiary-fixed': '#ffdbcc',
                'tertiary-fixed-dim': '#ffb695',
                'on-tertiary-fixed-variant': '#7b2f00',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                gutter: '24px',
                base: '4px',
                'container-padding': '32px',
                'sidebar-width': '260px',
                'section-gap': '48px',
                'sidebar-collapsed': '72px',
            },
            fontSize: {
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'mono-label': ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'display-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
            },
        },
    },

    plugins: [forms],
};
